- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: '2026-04-07T20:25:32Z'
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":5434,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: Mozilla
      operation: Update
      time: '2026-04-07T20:25:32Z'
    name: headless
    namespace: default
    resourceVersion: '65985'
    uid: 3494a983-1628-4958-84ad-d2613a7b564a
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: headless
      port: 5434
      protocol: TCP
      targetPort: 5434
    selector:
      network.kubevirt.io/headlessService: headless
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: '2026-04-07T16:27:05Z'
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:externalName: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: dns-operator
      operation: Update
      time: '2026-04-07T16:27:05Z'
    name: openshift
    namespace: default
    resourceVersion: '7635'
    uid: b8cead26-7c30-46a0-8933-2d79d0e18cd3
  spec:
    externalName: kubernetes.default.svc.cluster.local
    sessionAffinity: None
    type: ExternalName
